[build-system]
# Since the build backend imports the entire module,
# all runtime dependencies are also build dependencies.
requires = ["setuptools", "wheel", "PyGObject", "PyYAML"]
backend-path = ["."]
build-backend = "build"
