# Publish releases to PyPI automatically.
name: Publish Release

on:
  release:
    types: [ published ]

  # Enable running this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo under ${GITHUB_WORKSPACE}, so the job can access it.
      - uses: actions/checkout@v2

      # Use some off-the-shelf thing.
      - name: Publish Release
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
