# Publish releases to PyPI automatically.
name: Publish Release

on:
  release:
    types: [ published ]

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/terminalle
    permissions:
      # Mandatory for trusted publishing with `gh-action-pypi-publish`.
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Build the package
        run: |
          python -m pip install build
          python -m build

      - uses: pypa/gh-action-pypi-publish@release/v1
