# Publish releases to PyPI automatically.
name: Publish Release

on:
  release:
    types: [ published ]

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/terminalle
    permissions:
      # Mandatory for trusted publishing with `gh-action-pypi-publish`.
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version-file: 'pyproject.toml'

      # We could use `uv` for this instead of `pip`,
      # but that would require installing it,
      # which would cancel out the performance gain from avoiding `pip`.
      - name: Build the package
        run: |
          python -m pip install build
          python -m build

      - uses: pypa/gh-action-pypi-publish@release/v1
