# Publish releases to PyPI automatically.
name: Publish Release

on:
  release:
    types: [ published ]

jobs:
  pypi:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
      # Checkout the repo under ${GITHUB_WORKSPACE}, so the job can access it.
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build the package
        run: |
          python -m pip install build
          python -m build

      # Use some off-the-shelf thing.
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
